name: tbib_loading_transition_button_and_social
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  vector_math: ^2.1.0
  font_awesome_flutter:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  lint: ^1.3.1
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

 assets:
     - images/
